export {
  getAudioContext,
  resumeAudio,
  previewSound,
  setMasterVolume,
  getMasterVolume,
  readStoredVolume,
  storeVolume,
  playClick,
  playDrum,
  playWood,
  playClap,
  playHiHat,
  playVoice,
  playTick,
} from "./voices";
